# E/22/194

# Assignment 7: Kalman Filter

# Q1.

### Assumptions

$$w_{k-1} \sim \mathscr{N}(0,\Sigma_p)$$

$$z_k \sim \mathscr{N}(0,\Sigma_m)$$


### 1.

Because the state transition equation is a linear combination of Gaussian random variables, the predicted state $x_k^-$ is also Gaussian.

Mean:

$$m_k^- \triangleq \mathbb{E}[x^{-}_k] = \mathbb{E}[A_{k-1}x^{+}_{k-1} + G_{k-1}w_{k-1}]$$

since $\mathbb{E}[w_{k-1}] = 0$

$$m_k^- = A_{k-1}\mathbb{E}[x^{+}_{k-1}] + G_{k-1}\mathbb{E}[w_{k-1}] = A_{k-1}m_{k-1}$$

Covariance:

$$P_k^- \triangleq \text{Var}(x^{-}_k) = A_{k-1}\text{Var}(x^{+}_{k-1})A_{k-1}^T + G_{k-1}\text{Var}(w_{k-1})G_{k-1}^T$$
$$P_k^- = A_{k-1}P_{k-1}A_{k-1}^T + G_{k-1}\Sigma_p G_{k-1}^T$$



### 2.
 $y_k^-$ is also Gaussian.

Mean:

$$\mathbb{E}[y^{-}_k] = \mathbb{E}[H_k x_k^- + z_k] = H_k \mathbb{E}[x_k^-] + \mathbb{E}[z_k]$$

Since $\mathbb{E}[z_k] = 0$

$$\mathbb{E}[y^{-}_k] = H_k m_k^-$$

Covariance:

Because $x_k^-$ and $z_k$ are independent:
$$\text{Var}(y^{-}_k) = H_k \text{Var}(x_k^-) H_k^T + \text{Var}(z_k)$$

$$\text{Var}(y^{-}_k) = H_k P_k^- H_k^T + \Sigma_m$$

### 3.

Cross Covariance:

$$\text{Cov}(x_k^-, y^{-}_k) = \mathbb{E}[(x_k^- - m_k^-)(y_k^- - \mathbb{E}[y_k^-])^T]$$

Substitute $y_k^- = H_k x_k^- + z_k$ and $\mathbb{E}[y_k^-] = H_k m_k^-$


$$y_k^- - \mathbb{E}[y_k^-] = (H_k x_k^- + z_k) - H_k m_k^- = H_k(x_k^- - m_k^-) + z_k$$


$$\text{Cov}(x_k^-, y^{-}_k) = \mathbb{E}[(x_k^- - m_k^-)(H_k(x_k^- - m_k^-) + z_k)^T]$$

$$\text{Cov}(x_k^-, y^{-}_k) = \mathbb{E}[(x_k^- - m_k^-)(x_k^- - m_k^-)^T H_k^T + (x_k^- - m_k^-)z_k^T]$$

Because the state $x_k^-$ and the measurement noise $z_k$ are independent,

$$\mathbb{E}[(x_k^- - m_k^-)z_k^T] = 0$$

$$\text{Cov}(x_k^-, y^{-}_k) = \mathbb{E}[(x_k^- - m_k^-)(x_k^- - m_k^-)^T] H_k^T = P_k^- H_k^T$$


$$\begin{bmatrix} x_k^- \\ y^{-}_k \end{bmatrix} \sim \mathscr{N}\left(
\begin{bmatrix} m_k^- \\ H_k m_k^- \end{bmatrix},
\begin{bmatrix} P_k^- & P_k^- H_k^T \\ H_k P_k^- & H_k P_k^- H_k^T + \Sigma_m \end{bmatrix}
\right)$$

### 4.

If variables $X$ and $Y$ are jointly Gaussian:
$$\begin{bmatrix} X \\ Y \end{bmatrix} \sim \mathscr{N}\left(\begin{bmatrix} \mu_X \\ \mu_Y \end{bmatrix}, \begin{bmatrix} \Sigma_{XX} & \Sigma_{XY} \\ \Sigma_{YX} & \Sigma_{YY} \end{bmatrix}\right)$$

The conditional distribution $X \mid Y=y$ is $\mathscr{N}(\mu_{X|Y}, \Sigma_{X|Y})$,

where:
$$\mu_{X|Y} = \mu_X + \Sigma_{XY}\Sigma_{YY}^{-1}(y - \mu_Y)$$

$$\Sigma_{X|Y} = \Sigma_{XX} - \Sigma_{XY}\Sigma_{YY}^{-1}\Sigma_{YX}$$
Here
* $\mu_X = m_k^-$
* $\mu_Y = H_k m_k^-$
* $\Sigma_{XX} = P_k^-$
* $\Sigma_{YY} = H_k P_k^- H_k^T + \Sigma_m$
* $\Sigma_{XY} = P_k^- H_k^T$


$$K_k \triangleq P_k^- H_k^T (H_k P_k^- H_k^T + \Sigma_m)^{-1}$$


$$m_k = m_k^- + K_k(y^{\mathrm{obs}}_{k} - H_k m_k^-)$$


$$P_k = P_k^- - K_k(H_k P_k^-)$$

$$P_k = (I - K_k H_k) P_k^-$$

### 5.



Expected Value (Conditional Mean):

$$\mathbb{E}[x^{-}_k \mid y^{-}_k = y^{\mathrm{obs}}_{k}] = m_k = m_k^- + K_k (y^{\mathrm{obs}}_{k} - H_k m_k^-)$$

Variance (Conditional Covariance):

$$\text{Var}(x^{-}_k \mid y^{-}_k = y^{\mathrm{obs}}_{k}) = P_k = (I - K_k H_k) P_k^-$$

# Q. 1-D Example

### 1.

Given the state transition model:

$$x^-_k = a\,x^+_{k-1} + w_{k-1}$$

where $w_{k-1} \sim \mathscr{N}(0,q)$ and is independent of $x^+_{k-1} \sim \mathscr{N}(m_{k-1}, P_{k-1})$.


$$m_k^- = \mathbb{E}[x^-_k \mid Y_{k-1}] = \mathbb{E}[a\,x^+_{k-1} + w_{k-1}]$$

since $\mathbb{E}[w_{k-1}] = 0$:

$$m_k^- = a\,\mathbb{E}[x^+_{k-1}] + 0 = a\,m_{k-1}$$

$$P_k^- = \text{Var}(x^-_k \mid Y_{k-1}) = \text{Var}(a\,x^+_{k-1}) + \text{Var}(w_{k-1})$$

By using  $$\text{Var}(cX) = c^2\text{Var}(X)$$

$$P_k^- = a^2 \text{Var}(x^+_{k-1}) + q = a^2 P_{k-1} + q$$

### 2.


The cross-covariance between state and measurement is:

$$\text{Cov}(x^-_k, y^-_k) = \text{Cov}(x^-_k, h\,x^-_k + z_k) = h\,\text{Var}(x^-_k) = h\,P_k^-$$

The innovation covariance $S_k$ is:
$$\text{Var}(y^-_k) = \text{Var}(h\,x^-_k + z_k) = h^2 P_k^- + r = S_k$$


$$m_k = m_k^- + \text{Cov}(x^-_k, y^-_k) \text{Var}(y^-_k)^{-1} (y^{\mathrm{obs}}_k - \mathbb{E}[y^-_k])$$

$$m_k = m_k^- + (P_k^- h)(S_k)^{-1} v_k$$

Defining the Kalman gain as $$K_k = \frac{P_k^- h}{S_k}$$

Then

$$m_k = m_k^- + K_k\,v_k$$


$$P_k = \text{Var}(x^-_k) - \text{Cov}(x^-_k, y^-_k) \text{Var}(y^-_k)^{-1} \text{Cov}(y^-_k, x^-_k)$$

$$P_k = P_k^- - (P_k^- h)(S_k)^{-1}(h P_k^-)$$

$$P_k = P_k^- - K_k h P_k^- = (1 - K_k h) P_k^-$$

### 3.

Since $x^-_k \mid Y_{k-1} \sim \mathscr{N}(m_k^-, P_k^-)$ and $z_k \sim \mathscr{N}(0,r)$ are independent Gaussian variables, their linear combination is also Gaussian.

Expected value:

$$\mathbb{E}[y^-_k \mid Y_{k-1}] = h\,\mathbb{E}[x^-_k \mid Y_{k-1}] + \mathbb{E}[z_k] = h\,m_k^-$$

Variance: $$\text{Var}(y^-_k \mid Y_{k-1}) = h^2\text{Var}(x^-_k \mid Y_{k-1}) + \text{Var}(z_k) = h^2 P_k^- + r$$

Thus,

$$p(y^-_k \mid Y_{k-1}) = \mathscr{N}(h\,m_k^-,\; h^2 P_k^- + r)$$

### 4.

Expected value: $$\mathbb{E}[y^-_k \mid Y_k] = h\,\mathbb{E}[x_k \mid Y_k] + \mathbb{E}[z_k] = h\,m_k$$

Variance: $$\text{Var}(y^-_k \mid Y_k) = h^2\text{Var}(x_k \mid Y_k) + \text{Var}(z_k) = h^2 P_k + r$$

Thus, $$p(y^-_k \mid Y_k) = \mathscr{N}(h\,m_k,\; h^2 P_k + r)$$

In [3]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# -----------------------------
# Gaussian PDF
# -----------------------------
def gaussian_pdf(x, mean, var):
    return (1 / np.sqrt(2 * np.pi * var)) * np.exp(-0.5 * ((x - mean) ** 2) / var)

# -----------------------------
# Parameters
# -----------------------------
a = 1.0      # state transition
q = 0.5      # process noise variance
h = 1.0      # measurement model
r = 1.5      # measurement noise variance

m0 = 0.0
P0 = 2.0
num_steps = 20

np.random.seed(42)

# -----------------------------
# Generate true state and measurements
# -----------------------------
x_true = np.zeros(num_steps)
y_obs = np.zeros(num_steps)

x_true[0] = m0

for k in range(1, num_steps):
    x_true[k] = a * x_true[k - 1] + np.random.normal(0, np.sqrt(q))
    y_obs[k] = h * x_true[k] + np.random.normal(0, np.sqrt(r))

# -----------------------------
# Kalman filter arrays
# -----------------------------
m_minus = np.zeros(num_steps)
P_minus = np.zeros(num_steps)

m_plus = np.zeros(num_steps)
P_plus = np.zeros(num_steps)

K_gain = np.zeros(num_steps)
innovation = np.zeros(num_steps)

m_plus[0] = m0
P_plus[0] = P0

# -----------------------------
# Run Kalman Filter
# -----------------------------
for k in range(1, num_steps):
    # Prediction
    m_minus[k] = a * m_plus[k - 1]
    P_minus[k] = a**2 * P_plus[k - 1] + q

    # Update
    S_k = h**2 * P_minus[k] + r
    K_gain[k] = P_minus[k] * h / S_k
    innovation[k] = y_obs[k] - h * m_minus[k]

    m_plus[k] = m_minus[k] + K_gain[k] * innovation[k]
    P_plus[k] = (1 - K_gain[k] * h) * P_minus[k]

# -----------------------------
# Grid for distributions
# -----------------------------
x_min = min(x_true.min(), (y_obs / h).min(), m_minus.min(), m_plus.min()) - 5
x_max = max(x_true.max(), (y_obs / h).max(), m_minus.max(), m_plus.max()) + 5
x_grid = np.linspace(x_min, x_max, 600)

def get_curves(k):
    prior = gaussian_pdf(x_grid, m_minus[k], P_minus[k])
    posterior = gaussian_pdf(x_grid, m_plus[k], P_plus[k])

    # Measurement likelihood p(y_obs | x)
    likelihood = np.exp(-0.5 * ((y_obs[k] - h * x_grid) ** 2) / r)
    likelihood = likelihood / likelihood.max()
    likelihood = likelihood * max(prior.max(), posterior.max())

    return prior, likelihood, posterior

# -----------------------------
# Initial frame
# -----------------------------
k0 = 1
prior, likelihood, posterior = get_curves(k0)

fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=[
        "Prior + Measurement + Posterior",
        "True State vs Measurement vs Estimate"
    ]
)

# Left plot
fig.add_trace(go.Scatter(x=x_grid, y=prior, name="Prior", line=dict(dash="dash")), row=1, col=1)
fig.add_trace(go.Scatter(x=x_grid, y=likelihood, name="Measurement Likelihood", line=dict(dash="dot")), row=1, col=1)
fig.add_trace(go.Scatter(x=x_grid, y=posterior, name="Posterior"), row=1, col=1)

fig.add_trace(go.Scatter(x=[x_true[k0], x_true[k0]], y=[0, 1], name="True State", mode="lines"), row=1, col=1)

# Right plot
time = np.arange(num_steps)

fig.add_trace(go.Scatter(x=time, y=x_true, name="True State Path"), row=1, col=2)
fig.add_trace(go.Scatter(x=time, y=y_obs / h, name="Measurements", mode="markers"), row=1, col=2)
fig.add_trace(go.Scatter(x=time, y=m_plus, name="Kalman Estimate"), row=1, col=2)

fig.add_trace(go.Scatter(x=[k0], y=[x_true[k0]], name="Current True", mode="markers", marker=dict(size=14)), row=1, col=2)
fig.add_trace(go.Scatter(x=[k0], y=[y_obs[k0] / h], name="Current Measurement", mode="markers", marker=dict(size=14)), row=1, col=2)
fig.add_trace(go.Scatter(x=[k0], y=[m_plus[k0]], name="Current Estimate", mode="markers", marker=dict(size=14)), row=1, col=2)

# -----------------------------
# Frames
# -----------------------------
frames = []

for k in range(1, num_steps):
    prior, likelihood, posterior = get_curves(k)

    frames.append(
        go.Frame(
            data=[
                go.Scatter(x=x_grid, y=prior),
                go.Scatter(x=x_grid, y=likelihood),
                go.Scatter(x=x_grid, y=posterior),
                go.Scatter(x=[x_true[k], x_true[k]], y=[0, 1]),
                go.Scatter(x=[k], y=[x_true[k]]),
                go.Scatter(x=[k], y=[y_obs[k] / h]),
                go.Scatter(x=[k], y=[m_plus[k]])
            ],
            traces=[0, 1, 2, 3, 7, 8, 9],
            name=str(k)
        )
    )

fig.frames = frames

# -----------------------------
# Slider and buttons
# -----------------------------
steps = []

for k in range(1, num_steps):
    steps.append(
        dict(
            method="animate",
            args=[
                [str(k)],
                dict(
                    frame=dict(duration=500, redraw=True),
                    transition=dict(duration=200),
                    mode="immediate"
                )
            ],
            label=str(k)
        )
    )

fig.update_layout(
    title="Visual Kalman Filter Animation",
    width=1200,
    height=600,
    template="plotly_white",
    sliders=[
        dict(
            active=0,
            currentvalue=dict(prefix="Time step: "),
            steps=steps
        )
    ],
    updatemenus=[
        dict(
            type="buttons",
            x=0.1,
            y=-0.15,
            buttons=[
                dict(
                    label="Play",
                    method="animate",
                    args=[
                        None,
                        dict(frame=dict(duration=700, redraw=True), fromcurrent=True)
                    ]
                ),
                dict(
                    label="Pause",
                    method="animate",
                    args=[
                        [None],
                        dict(frame=dict(duration=0), mode="immediate")
                    ]
                )
            ]
        )
    ]
)

fig.update_xaxes(title_text="State value x", row=1, col=1)
fig.update_yaxes(title_text="Probability density", row=1, col=1)

fig.update_xaxes(title_text="Time step", row=1, col=2)
fig.update_yaxes(title_text="State value", row=1, col=2)

fig.show()

# Q2

### Part A

For a 2D constant velocity model,

Let  apply standard Newtonian kinematics.

Given a time sampling interval $\Delta t$,

$$p_x(k) = p_x(k-1) + \Delta t\, v_x(k-1)$$
$$p_y(k) = p_y(k-1) + \Delta t\, v_y(k-1)$$
$$v_x(k) = v_x(k-1)$$
$$v_y(k) = v_y(k-1)$$

Let it  $x_k = A x_{k-1}$

$$
\begin{bmatrix}
p_x(k)\\
p_y(k)\\
v_x(k)\\
v_y(k)
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & \Delta t & 0\\
0 & 1 & 0 & \Delta t\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
p_x(k-1)\\
p_y(k-1)\\
v_x(k-1)\\
v_y(k-1)
\end{bmatrix}
$$

Therefore, the state transition matrix is:

$$
A =
\begin{bmatrix}
1 & 0 & \Delta t & 0\\
0 & 1 & 0 & \Delta t\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}
$$

$$y_k = H x_k$$

$$p_x^{\mathrm{meas}}(k) = 1 \cdot p_x(k) + 0 \cdot p_y(k) + 0 \cdot v_x(k) + 0 \cdot v_y(k)$$

$$p_y^{\mathrm{meas}}(k) = 0 \cdot p_x(k) + 1 \cdot p_y(k) + 0 \cdot v_x(k) + 0 \cdot v_y(k)$$



$$
\begin{bmatrix}
p_x^{\mathrm{meas}}(k)\\
p_y^{\mathrm{meas}}(k)
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
p_x(k)\\
p_y(k)\\
v_x(k)\\
v_y(k)
\end{bmatrix}
$$

Therefore, the measurement matrix is
$$
H =
\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0
\end{bmatrix}
$$


Let the process noise vector be $w_{k-1} = [a_x(k-1), a_y(k-1)]^T$, where $a_x$ and $a_y$ are the random accelerations along the $x$ and $y$ axes.


Adding these noise contributions

$$p_x(k) = p_x(k-1) + \Delta t\, v_x(k-1) + \frac{1}{2}\Delta t^2\, a_x(k-1)$$
$$p_y(k) = p_y(k-1) + \Delta t\, v_y(k-1) + \frac{1}{2}\Delta t^2\, a_y(k-1)$$
$$v_x(k) = v_x(k-1) + \Delta t\, a_x(k-1)$$
$$v_y(k) = v_y(k-1) + \Delta t\, a_y(k-1)$$

The deterministic terms are handled by $A x_{k-1}$.

The remaining terms represent the stochastic perturbation $G w_{k-1}$:

$$
G w_{k-1} =
\begin{bmatrix}
\frac{1}{2}\Delta t^2 \cdot a_x(k-1)\\
\frac{1}{2}\Delta t^2 \cdot a_y(k-1)\\
\Delta t \cdot a_x(k-1)\\
\Delta t \cdot a_y(k-1)
\end{bmatrix}
$$

Factoring out the acceleration noise vector $w_{k-1} = [a_x(k-1), a_y(k-1)]^T$,

Isolate the matrix $G$:

$$
G w_{k-1} =
\begin{bmatrix}
\frac{1}{2}\Delta t^2 & 0\\
0 & \frac{1}{2}\Delta t^2\\
\Delta t & 0\\
0 & \Delta t
\end{bmatrix}
\begin{bmatrix}
a_x(k-1)\\
a_y(k-1)
\end{bmatrix}
$$

Therefore, the process noise input matrix is:
$$
G =
\begin{bmatrix}
\frac{1}{2}\Delta t^2 & 0\\
0 & \frac{1}{2}\Delta t^2\\
\Delta t & 0\\
0 & \Delta t
\end{bmatrix}
$$



### Part B



In [4]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [5]:
def kalman_filter_2d_gps(gps_measurements, dt=1.0, sigma_acc=0.35, sigma_gps=2.5):
    gps_measurements = np.asarray(gps_measurements)
    n = len(gps_measurements)

    A = np.array([
        [1, 0, dt, 0],
        [0, 1, 0, dt],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

    H = np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0]
    ])

    G = np.array([
        [0.5 * dt**2, 0],
        [0, 0.5 * dt**2],
        [dt, 0],
        [0, dt]
    ])

    Sigma_p = np.diag([sigma_acc**2, sigma_acc**2])
    Sigma_m = np.diag([sigma_gps**2, sigma_gps**2])

    Q = G @ Sigma_p @ G.T
    R = Sigma_m

    x_pred = np.zeros((n, 4))
    P_pred = np.zeros((n, 4, 4))
    x_filt = np.zeros((n, 4))
    P_filt = np.zeros((n, 4, 4))

    x_filt[0] = np.array([gps_measurements[0, 0], gps_measurements[0, 1], 0.0, 0.0])
    P_filt[0] = np.diag([sigma_gps**2, sigma_gps**2, 10.0, 10.0])

    I = np.eye(4)

    for k in range(1, n):
        x_pred[k] = A @ x_filt[k - 1]
        P_pred[k] = A @ P_filt[k - 1] @ A.T + Q

        y_k = gps_measurements[k]
        y_pred = H @ x_pred[k]
        innovation = y_k - y_pred

        S = H @ P_pred[k] @ H.T + R
        K = P_pred[k] @ H.T @ np.linalg.inv(S)

        x_filt[k] = x_pred[k] + K @ innovation
        P_filt[k] = (I - K @ H) @ P_pred[k] @ (I - K @ H).T + K @ R @ K.T

    return x_filt, P_filt, A, H, G, Q, R

In [6]:
np.random.seed(10)

dt = 1.0
num_steps = 80

true_state = np.zeros((num_steps, 4))
true_state[0] = np.array([0.0, 0.0, 1.2, 0.7])

true_sigma_acc = 0.15
gps_sigma = 2.5

for k in range(1, num_steps):
    ax = np.random.normal(0, true_sigma_acc)
    ay = np.random.normal(0, true_sigma_acc)

    true_state[k, 0] = true_state[k - 1, 0] + dt * true_state[k - 1, 2] + 0.5 * dt**2 * ax
    true_state[k, 1] = true_state[k - 1, 1] + dt * true_state[k - 1, 3] + 0.5 * dt**2 * ay
    true_state[k, 2] = true_state[k - 1, 2] + dt * ax
    true_state[k, 3] = true_state[k - 1, 3] + dt * ay

gps_measurements = true_state[:, :2] + np.random.normal(0, gps_sigma, size=(num_steps, 2))

x_filt, P_filt, A, H, G, Q, R = kalman_filter_2d_gps(
    gps_measurements,
    dt=dt,
    sigma_acc=0.35,
    sigma_gps=gps_sigma
)

gps_error = np.linalg.norm(gps_measurements - true_state[:, :2], axis=1)
kf_error = np.linalg.norm(x_filt[:, :2] - true_state[:, :2], axis=1)

gps_rmse = np.sqrt(np.mean(gps_error**2))
kf_rmse = np.sqrt(np.mean(kf_error**2))

print("===== 2D GPS Kalman Filter Results =====")
print(f"GPS Position RMSE  : {gps_rmse:.3f} m")
print(f"Kalman Filter RMSE : {kf_rmse:.3f} m")
print()
print("A matrix:")
print(A)
print()
print("H matrix:")
print(H)
print()
print("G matrix:")
print(G)

===== 2D GPS Kalman Filter Results =====
GPS Position RMSE  : 3.397 m
Kalman Filter RMSE : 2.125 m

A matrix:
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

H matrix:
[[1 0 0 0]
 [0 1 0 0]]

G matrix:
[[0.5 0. ]
 [0.  0.5]
 [1.  0. ]
 [0.  1. ]]


In [7]:
time = np.arange(num_steps)

fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=["2D GPS Tracking", "Position Error Over Time"],
    column_widths=[0.6, 0.4]
)

fig.add_trace(
    go.Scatter(x=true_state[:, 0], y=true_state[:, 1],
               mode="lines", name="True Path", line=dict(width=4)),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=gps_measurements[:, 0], y=gps_measurements[:, 1],
               mode="markers", name="Noisy GPS", marker=dict(size=7, opacity=0.55)),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=x_filt[:, 0], y=x_filt[:, 1],
               mode="lines+markers", name="Kalman Estimate",
               line=dict(width=4), marker=dict(size=5)),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=time, y=gps_error, mode="lines",
               name="GPS Error", line=dict(width=3, dash="dot")),
    row=1, col=2
)

fig.add_trace(
    go.Scatter(x=time, y=kf_error, mode="lines",
               name="Kalman Filter Error", line=dict(width=3)),
    row=1, col=2
)

fig.update_layout(
    title="2D Constant-Velocity Kalman Filter for Noisy GPS",
    template="plotly_white",
    width=1200,
    height=600
)

fig.update_xaxes(title_text="x-position", row=1, col=1)
fig.update_yaxes(title_text="y-position", scaleanchor="x", scaleratio=1, row=1, col=1)

fig.update_xaxes(title_text="Time Step", row=1, col=2)
fig.update_yaxes(title_text="Position Error", row=1, col=2)

fig.show()

In [8]:
frames = []

for k in range(num_steps):
    frames.append(
        go.Frame(
            data=[
                go.Scatter(x=true_state[:k+1, 0], y=true_state[:k+1, 1],
                           mode="lines", name="True Path", line=dict(width=4)),
                go.Scatter(x=gps_measurements[:k+1, 0], y=gps_measurements[:k+1, 1],
                           mode="markers", name="Noisy GPS", marker=dict(size=7, opacity=0.6)),
                go.Scatter(x=x_filt[:k+1, 0], y=x_filt[:k+1, 1],
                           mode="lines+markers", name="Kalman Estimate",
                           line=dict(width=4), marker=dict(size=5)),
                go.Scatter(x=[true_state[k, 0]], y=[true_state[k, 1]],
                           mode="markers", name="Current True State",
                           marker=dict(size=14, symbol="circle")),
                go.Scatter(x=[gps_measurements[k, 0]], y=[gps_measurements[k, 1]],
                           mode="markers", name="Current GPS",
                           marker=dict(size=14, symbol="x")),
                go.Scatter(x=[x_filt[k, 0]], y=[x_filt[k, 1]],
                           mode="markers", name="Current KF Estimate",
                           marker=dict(size=14, symbol="diamond"))
            ],
            name=str(k)
        )
    )

fig_anim = go.Figure(data=frames[0].data, frames=frames)

steps = []
for k in range(num_steps):
    steps.append(
        dict(
            method="animate",
            args=[[str(k)],
                  dict(mode="immediate",
                       frame=dict(duration=500, redraw=True),
                       transition=dict(duration=200))],
            label=str(k)
        )
    )

x_min = min(true_state[:, 0].min(), gps_measurements[:, 0].min(), x_filt[:, 0].min()) - 5
x_max = max(true_state[:, 0].max(), gps_measurements[:, 0].max(), x_filt[:, 0].max()) + 5

y_min = min(true_state[:, 1].min(), gps_measurements[:, 1].min(), x_filt[:, 1].min()) - 5
y_max = max(true_state[:, 1].max(), gps_measurements[:, 1].max(), x_filt[:, 1].max()) + 5

fig_anim.update_layout(
    title="Animated 2D GPS Kalman Filter Tracking",
    template="plotly_white",
    width=900,
    height=700,
    xaxis_title="x-position",
    yaxis_title="y-position",
    xaxis=dict(range=[x_min, x_max]),
    yaxis=dict(range=[y_min, y_max], scaleanchor="x", scaleratio=1),
    sliders=[dict(active=0, currentvalue=dict(prefix="Time Step: "), steps=steps)],
    updatemenus=[
        dict(
            type="buttons",
            showactive=False,
            x=0.1,
            y=-0.12,
            buttons=[
                dict(label="Play", method="animate",
                     args=[None, dict(frame=dict(duration=500, redraw=True),
                                      transition=dict(duration=200),
                                      fromcurrent=True)]),
                dict(label="Pause", method="animate",
                     args=[[None], dict(frame=dict(duration=0, redraw=False),
                                        mode="immediate")])
            ]
        )
    ]
)

fig_anim.show()



The raw GPS measurements are noisy because they contain measurement noise.

The Kalman Filter uses a constant-velocity motion model to predict the next state and then corrects that prediction using the GPS measurement.

The filter estimates both position and velocity:

\[
x_k =
\begin{bmatrix}
p_x\\
p_y\\
v_x\\
v_y
\end{bmatrix}
\]

even though the GPS measurement contains only position:

\[
y_k =
\begin{bmatrix}
p_x^{meas}\\
p_y^{meas}
\end{bmatrix}
\]

The filtered trajectory is smoother than the raw GPS measurements because the Kalman Filter balances the motion model and the noisy GPS data.